# -*- coding: utf-8 -*-
"""Personal_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wkheSdxeL_suHIgwhys3OIXv1hl2zqVB

<b>Scraping Data</b>
"""

from urllib.request import Request, urlopen
from bs4 import BeautifulSoup

"""In order to avoid the 404 HTTP Error:"""

SITE = "https://neurosciencenews.com/dog-numeracy-15326/"
HDR = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A'}
req = Request(SITE, headers = HDR)
page = urlopen(req)
soup = BeautifulSoup(page, 'html.parser')

p_list = soup.find_all('p')
for p in p_list:
    print (p)
    #print (p.get_text()+"\n") ###G: Remove this old comment

print (soup.title.get_text())

import re
title = soup.title.get_text()
fileName = re.sub('[^A-Za-z0-9]+ ', '', title)+".html"
f= open(fileName ,"w+") 
'''f.truncate(0) 
f.write("<body>")
f.write (title + "\n\n\n\n")#"<h2>" + title + "</h2>" + "<br><br>")
for p in p_list:
    f.write(p.get_text()+"\n\n")
f.write("</body>")
'''
f.write("<!doctype html>")
f.write("<html>")
f.write("<head>")
f.write("<title>" + "Date put here..." + "</title>") 
f.write("<meta http-equiv='content-type' content='text/html; charset=iso-8859-1'>")
f.write("<head>")	 
f.write("</head>") 
f.write("<body>") 
f.write("<h2>List of articles published on DATE:<h2>") 
f.write("<a href='#anchor-name'>" + "Jump to the part of the page with the “anchor-name” id" + "</a>")   
f.write("<h1>" + title + "</h1>")   
for p in p_list:
    f.write(p.get_text()+"\n\n")
f.write("<h1>" + title + "</h1>")   
for p in p_list:
    f.write(p.get_text()+"\n\n")
f.write("<h1 id='anchor-name'>" + title + "</h1>")   
for p in p_list:
    f.write(p.get_text()+"\n\n")
f.write("</body>")
f.write("</html>")
	


f.close()



"""THIS IS NOT WORKING BECAUSE IT'S A LIBLARY FOR MAC:

from kindle_maker import make_mobi

source_dir = fileName
output_dir = "Grigor_Done.mobi"
make_mobi(source_dir, output_dir)

This is link to converting html2mobi and sending it to an email: https://github.com/moshfiqur/html2mobi 🍬
"""

from subprocess import call

print(fileName)
#call(["./kindlegen", fileName])
call(["tools/kindlegen", fileName])

"""So far it works but it doesn't like the html tags. It also is messy as a file - no spacing. Task for next time: figure out how to edit it

<b>Sending the mobi to kindle email:</b>
"""



import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.utils import formatdate
from email import encoders

msg = MIMEMultipart()
send_from = msg['From'] = 'cognitivemashup@gmail.com'
PASSWORD = "Lilyismydog10"
send_to = msg['To'] = 'sandra.machon@kindle.com' # Can be 'Send to Kindle' email
msg['Date'] = formatdate(localtime=True)
msg['Subject'] = fileName + ".mobi"

# Attache email body
#msg.attach(MIMEText('Want to write a customized email boddy? Then put it here.'))

# Attach the .mobi file
fp = open(fileName, "rb")
mobi_file = MIMEApplication(fp.read())
fp.close()
encoders.encode_base64(mobi_file)
mobi_file.add_header('Content-Disposition', 'attachment; filename="%s"' % fileName + '.mobi')
msg.attach(mobi_file)

# Send the email
'''
try:
    server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
    server.ehlo()
    #server.starttls()
    server.login(send_from, PASSWORD)   #make sure to enable less secure apps in google preferences: https://myaccount.google.com/lesssecureapps
    server.sendmail(send_from, send_to, msg.as_string())
    server.close()
    print( 'successfully sent the mail' )
except Exception as e:
    print( e)
'''
"""<b>For the next time:</b> 
-Figure out how to send a nicer formed mobi (with pictures, title,bold abstract and meta data)
-Figure out how to set up a server which will update the articles and send it once week
-Figure out if you want to use another url
😎
"""

